### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by osorensen** [DIDSR/WebXR-tools#10]
I could not find any automated tests for this software, nor any description of manual steps for confirming the validity.

Ideally, you could use continuous integration tests via [GitHub actions](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs).

This relates to the following review item:

<img width="805" alt="image" src="https://github.com/DIDSR/WebXR-tools/assets/21175639/ca7d37d3-2d07-463f-979f-90ec68b1358f">

https://github.com/openjournals/joss-reviews/issues/6021

**Comment by brendanc490** [comment]
The testing procedures were not easy to find, I apologize. Here is the link to the tests: https://github.com/DIDSR/WebXR-tools/blob/JOSS-Submission/Custom/README.md. I have opted for manual testing in this case because the tool itself is a user interface that heavily relies on human interaction. The linked README file contains a series of tests that can be walked through. I wanted to ensure that task completion is easy and understandable.

**Comment by osorensen** [comment]
Thanks, I went through most of the procedure and verified that it works. Some minor comments to the instructions:

- I think correct spelling for the control tab is "Ctrl", with capital "C".
- On Mac, I had to use the command tab wherever you mention the control tab, even though there is a control tab on Mac keyboards as well. Perhaps at first mention of "Ctrl", you could add in parentheses something like "(alternatively Command on Mac)".

**Comment by brendanc490** [comment]
Thanks for pointing this out. I changed the spelling and capitalization of the Ctrl instructions as well as added information about how to complete them on Mac.
